#!/usr/bin/env python

import BaseHTTPServer
import cgi
import os
import subprocess as sp
import shutil
import sys

WORDS_FILE="~/Projects/Android-Gitslave/WordWars-Unity//Assets/Resources/Dictionary/master_dictionary.txt"
#import pdb; pdb.set_trace()

with open(os.path.expanduser(WORDS_FILE), 'r') as f:
    words = f.read().splitlines()

swords=[]
for i in xrange(0,len(words)-1):
    swords.append(''.join(sorted(words[i])))

del sys.argv[0]
letters=''
for word in sys.argv:
    for l in word:
        if l.islower():
            letters=letters+l

def word2dict(word):
    dic = {}
    for i in xrange(len(word)):
        l=word[i]
        if l in dic:
            dic[l]+=1
        else:
            dic[l]=1
    return dic

dic = word2dict(letters)

goodwords={}
for word in words:
    test = word2dict(word)
    good = True
    for k in test.keys():
        if k not in dic or dic[k]<test[k]:
            good=False
            break
    if good:
        if len(word) in goodwords:
            goodwords[len(word)].append(word)
        else:
            goodwords[len(word)] = [word]

count=0
for size in reversed(sorted(goodwords.keys())):
    for word in goodwords[size]:
        if count<10:
            count +=1
            print word
